In [1]:
import os

In [6]:
os.listdir("./")

['.idea',
 '.ipynb_checkpoints',
 'annotated_interactions.txt',
 'bash.sh',
 'eigen_chr1_500kb.txt',
 'filt_interactions.txt',
 'hg38.chrom_size',
 'keep_chrom.txt',
 'main.py',
 'modules',
 'output',
 'requirements.txt',
 'SRR400264_00.allValidPairs',
 'SRR400264_00.allValidPairs.hic',
 'test.py',
 'Untitled.ipynb',
 'workflow.pptx',
 '~$workflow.pptx']

In [3]:
from sklearn.preprocessing import  OneHotEncoder


In [4]:
enc = OneHotEncoder()
enc.fit([[0, 0, 3],
         [1, 1, 0],
         [0, 2, 1],
         [1, 0, 2]])

OneHotEncoder()

In [5]:
ans = enc.transform([[0, 1, 3]]).toarray() 


In [11]:
enc.fit([["A"],["C"],["T"],["G"]])

OneHotEncoder()

In [14]:
enc.transform([["A"],["G"],["T"],["T"],["C"]]).toarray()

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [42]:
a=enc.transform([["A"],["G"],["T"],["T"],["C"]])

In [43]:
a.toarray()

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [17]:
import numpy as np

In [20]:
a="ACTGATGCTAGTGTAGCA"
b=np.array(list(a)).reshape(-1,1)
enc.transform(b).toarray()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [22]:
import numpy as np
from scipy.sparse import csr_matrix

# Dense matrix (normal 2D array)
dense_matrix = np.array([[1, 0, 0],
                         [0, 2, 0],
                         [0, 0, 3],
                         [0, 0, 1],
                        ])

# Convert dense matrix to sparse matrix (CSR format)
sparse_matrix = csr_matrix(dense_matrix)

print("Dense Matrix:")
print(dense_matrix)

print("\nSparse Matrix:")
print(sparse_matrix)

Dense Matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 1]]

Sparse Matrix:
  (0, 0)	1
  (1, 1)	2
  (2, 2)	3
  (3, 2)	1


In [25]:
np.array(list("ACTG")).reshape(-1,1)

array([['A'],
       ['C'],
       ['T'],
       ['G']], dtype='<U1')

In [27]:
import pyfastx

In [28]:
fa = pyfastx.Fasta("./test.fa",uppercase=True)

In [37]:
fa["chr1"].name

'chr1'

In [38]:
a=fa["chr1"]

In [39]:
b=fa["chr1"]

In [40]:
a.seq

'ACTGATGCTTGTATGCTTAGTG'

In [41]:
b.seq

'ACTGATGCTTGTATGCTTAGTG'

In [45]:
import h5py
with h5py.File("./output/final_interactions.h5","w") as f:
    print("raw" in f)

False


In [87]:
with h5py.File("./output/temp_extract/temp_extract_15","r") as f:
    print(f["raw_label"].shape)
    # print(np.array(f["raw_label"]))
    print(f.get("raw").shape)
    print(np.array(f.get("raw"))[2].sum(axis=1))

(6, 1, 1)
(6, 2000, 20)
[4. 4. 4. ... 4. 4. 4.]


In [77]:
from scipy.sparse import csr_matrix


In [78]:
data_sparse = csr_matrix([[0, 0, 0], [4, 0, 0], [0, 0, 7]])
data_csr = data_sparse.tocsr()


In [84]:
data_csr.toarray()

array([[0, 0, 0],
       [4, 0, 0],
       [0, 0, 7]])

In [86]:
with h5py.File("./output/final_interactions_gzip.h5","r") as f:
    print(f["raw_label"].shape)
    # print(np.array(f["raw_label"]))
    print(f.get("raw").shape)
    print(np.array(f.get("raw"))[2].sum(axis=1))

(100, 1, 1)
(94, 2000, 20)
[4. 4. 4. ... 4. 4. 4.]


In [88]:
with h5py.File("./output/final_interactions.h5","r") as f:
    print(f["raw_label"].shape)
    # print(np.array(f["raw_label"]))
    print(f.get("raw").shape)
    print(np.array(f.get("raw"))[2].sum(axis=1))

(100, 1, 1)
(94, 2000, 20)
[4. 4. 4. ... 4. 4. 4.]


In [1]:
from dna2vec.multi_k_model import MultiKModel

filepath = 'input/dna2vec-20230705-0901-k3to8-100d-10c-32730Mbp-sliding-k0s.w2v'
mk_model = MultiKModel(filepath)

In [4]:
a = mk_model.vector('AAA')

In [19]:
a

array([ 4.50780e-02,  7.72100e-02, -1.76706e-01,  3.26820e-01,
        1.40459e-01,  8.32360e-02, -4.95850e-02,  9.62070e-02,
       -4.02159e-01,  1.47676e-01,  3.03783e-01, -1.10233e-01,
        1.27718e-01,  4.59070e-02,  1.82718e-01,  2.92419e-01,
        3.89690e-02,  8.76730e-02, -1.22357e-01, -2.19144e-01,
       -5.10790e-02, -6.57741e-01, -7.77400e-02, -2.20840e-01,
        3.06904e-01, -2.37720e-02, -2.12180e-01, -3.73480e-02,
        1.39664e-01,  4.31456e-01, -1.36412e-01, -1.51886e-01,
        1.27832e-01, -2.05802e-01, -1.14535e-01,  2.54527e-01,
       -5.44000e-04,  3.73012e-01, -1.79577e-01, -2.44162e-01,
       -1.16711e-01, -1.10882e-01,  1.03541e-01, -5.40540e-02,
       -9.38630e-02,  3.53369e-01,  1.02665e-01,  3.04960e-02,
       -1.71053e-01,  4.76510e-02,  1.33784e-01,  2.73713e-01,
        9.61800e-03,  3.11577e-01,  1.61272e-01, -2.59980e-01,
       -1.16358e-01,  1.13813e-01, -2.36904e-01,  8.80600e-03,
       -1.86800e-01, -4.16710e-01,  1.11650e-02,  2.329

In [16]:
import numpy as np

In [18]:
np.array([0] * 100).reshape(100,)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
from Bio.SeqUtils import seq1

In [10]:
sequence = "ACGATGCTGATGTTGTACA"
k=6
k_mer_list = [sequence[i:i+k] for i in range(len(sequence) - k + 1)]

In [11]:
k_mer_list

['ACGATG',
 'CGATGC',
 'GATGCT',
 'ATGCTG',
 'TGCTGA',
 'GCTGAT',
 'CTGATG',
 'TGATGT',
 'GATGTT',
 'ATGTTG',
 'TGTTGT',
 'GTTGTA',
 'TTGTAC',
 'TGTACA']

In [20]:
type(9)==list

False