In [1]:

import os

In [6]:
os.listdir("./")

['.idea',
 '.ipynb_checkpoints',
 'annotated_interactions.txt',
 'bash.sh',
 'eigen_chr1_500kb.txt',
 'filt_interactions.txt',
 'hg38.chrom_size',
 'keep_chrom.txt',
 'main.py',
 'modules',
 'output',
 'requirements.txt',
 'SRR400264_00.allValidPairs',
 'SRR400264_00.allValidPairs.hic',
 'test.py',
 'Untitled.ipynb',
 'workflow.pptx',
 '~$workflow.pptx']

In [3]:
from sklearn.preprocessing import OneHotEncoder


In [4]:
enc = OneHotEncoder()
enc.fit([[0, 0, 3],
         [1, 1, 0],
         [0, 2, 1],
         [1, 0, 2]])

OneHotEncoder()

In [5]:
ans = enc.transform([[0, 1, 3]]).toarray() 


In [11]:
enc.fit([["A"],["C"],["T"],["G"]])

OneHotEncoder()

In [14]:
enc.transform([["A"],["G"],["T"],["T"],["C"]]).toarray()

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [42]:
a=enc.transform([["A"],["G"],["T"],["T"],["C"]])

In [43]:
a.toarray()

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [17]:
import numpy as np

In [20]:
a="ACTGATGCTAGTGTAGCA"
b=np.array(list(a)).reshape(-1,1)
enc.transform(b).toarray()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [22]:
import numpy as np
from scipy.sparse import csr_matrix

# Dense matrix (normal 2D array)
dense_matrix = np.array([[1, 0, 0],
                         [0, 2, 0],
                         [0, 0, 3],
                         [0, 0, 1],
                        ])

# Convert dense matrix to sparse matrix (CSR format)
sparse_matrix = csr_matrix(dense_matrix)

print("Dense Matrix:")
print(dense_matrix)

print("\nSparse Matrix:")
print(sparse_matrix)

Dense Matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 1]]

Sparse Matrix:
  (0, 0)	1
  (1, 1)	2
  (2, 2)	3
  (3, 2)	1


In [25]:
np.array(list("ACTG")).reshape(-1,1)

array([['A'],
       ['C'],
       ['T'],
       ['G']], dtype='<U1')

In [27]:
import pyfastx

In [28]:
fa = pyfastx.Fasta("./test.fa",uppercase=True)

In [37]:
fa["chr1"].name

'chr1'

In [38]:
a=fa["chr1"]

In [39]:
b=fa["chr1"]

In [40]:
a.seq

'ACTGATGCTTGTATGCTTAGTG'

In [41]:
b.seq

'ACTGATGCTTGTATGCTTAGTG'

In [2]:
import h5py
# with h5py.File("./output/final_interactions.h5","w") as f:
#     print("raw" in f)

In [87]:
with h5py.File("./output/temp_extract/temp_extract_15","r") as f:
    print(f["raw_label"].shape)
    # print(np.array(f["raw_label"]))
    print(f.get("raw").shape)
    print(np.array(f.get("raw"))[2].sum(axis=1))

(6, 1, 1)
(6, 2000, 20)
[4. 4. 4. ... 4. 4. 4.]


In [23]:
with h5py.File("./output/prep_datasets_dna2vec_4kb_2kb_train.h5","r") as f:
    print(f.keys())
    print(f["X"].shape)
    # # print(np.array(f["raw_label"]))
    # print(f.get("raw").shape)
    print(f.get("y").shape)
    # print(np.array(f.get("raw"))[2].sum(axis=1))

<KeysViewHDF5 ['X', 'y']>
(80, 6000, 100)
(80, 1, 1)


In [77]:
from scipy.sparse import csr_matrix


In [7]:
max(['4.36 GB', '4.70 GB', '4.88 GB', '5.02 GB', '5.10 GB', '4.71 GB', '4.80 GB', '4.88 GB', '4.97 GB', '5.01 GB', '5.10 GB', '5.25 GB', '5.34 GB', '4.76 GB', '637.36 MB'])

'637.36 MB'

In [78]:
data_sparse = csr_matrix([[0, 0, 0], [4, 0, 0], [0, 0, 7]])
data_csr = data_sparse.tocsr()


In [84]:
data_csr.toarray()

array([[0, 0, 0],
       [4, 0, 0],
       [0, 0, 7]])

In [86]:
with h5py.File("./output/final_interactions_gzip.h5","r") as f:
    print(f["raw_label"].shape)
    # print(np.array(f["raw_label"]))
    print(f.get("raw").shape)
    print(np.array(f.get("raw"))[2].sum(axis=1))

(100, 1, 1)
(94, 2000, 20)
[4. 4. 4. ... 4. 4. 4.]


In [88]:
with h5py.File("./output/final_interactions.h5","r") as f:
    print(f["raw_label"].shape)
    # print(np.array(f["raw_label"]))
    print(f.get("raw").shape)
    print(np.array(f.get("raw"))[2].sum(axis=1))

(100, 1, 1)
(94, 2000, 20)
[4. 4. 4. ... 4. 4. 4.]


In [1]:
from dna2vec.multi_k_model import MultiKModel

filepath = 'input/dna2vec-20230705-0901-k3to8-100d-10c-32730Mbp-sliding-k0s.w2v'
mk_model = MultiKModel(filepath)

In [4]:
a = mk_model.vector('AAA')

In [19]:
a

array([ 4.50780e-02,  7.72100e-02, -1.76706e-01,  3.26820e-01,
        1.40459e-01,  8.32360e-02, -4.95850e-02,  9.62070e-02,
       -4.02159e-01,  1.47676e-01,  3.03783e-01, -1.10233e-01,
        1.27718e-01,  4.59070e-02,  1.82718e-01,  2.92419e-01,
        3.89690e-02,  8.76730e-02, -1.22357e-01, -2.19144e-01,
       -5.10790e-02, -6.57741e-01, -7.77400e-02, -2.20840e-01,
        3.06904e-01, -2.37720e-02, -2.12180e-01, -3.73480e-02,
        1.39664e-01,  4.31456e-01, -1.36412e-01, -1.51886e-01,
        1.27832e-01, -2.05802e-01, -1.14535e-01,  2.54527e-01,
       -5.44000e-04,  3.73012e-01, -1.79577e-01, -2.44162e-01,
       -1.16711e-01, -1.10882e-01,  1.03541e-01, -5.40540e-02,
       -9.38630e-02,  3.53369e-01,  1.02665e-01,  3.04960e-02,
       -1.71053e-01,  4.76510e-02,  1.33784e-01,  2.73713e-01,
        9.61800e-03,  3.11577e-01,  1.61272e-01, -2.59980e-01,
       -1.16358e-01,  1.13813e-01, -2.36904e-01,  8.80600e-03,
       -1.86800e-01, -4.16710e-01,  1.11650e-02,  2.329

In [16]:
import numpy as np

In [18]:
np.array([0] * 100).reshape(100,)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
from Bio.SeqUtils import seq1

In [10]:
sequence = "ACGATGCTGATGTTGTACA"
k=6
k_mer_list = [sequence[i:i+k] for i in range(len(sequence) - k + 1)]

In [11]:
k_mer_list

['ACGATG',
 'CGATGC',
 'GATGCT',
 'ATGCTG',
 'TGCTGA',
 'GCTGAT',
 'CTGATG',
 'TGATGT',
 'GATGTT',
 'ATGTTG',
 'TGTTGT',
 'GTTGTA',
 'TTGTAC',
 'TGTACA']

In [20]:
type(9)==list

False

In [1]:
import torch
import h5py

In [42]:
X,y=torch.load("output/prep_datasets_train.pt")

FileNotFoundError: [Errno 2] No such file or directory: 'output/prep_datasets_train.pt'

In [26]:
X[0,850]

array([ 0.16530199,  0.438613  ,  0.44953501, -0.37554801,  0.054362  ,
        0.00718   ,  0.070044  ,  0.332537  , -0.042109  ,  0.008692  ,
       -0.21987399,  0.36284301,  0.17488401,  0.351441  ,  0.193244  ,
        0.37198201, -0.126081  , -0.47820699,  0.04093   , -0.200571  ,
        0.126065  , -0.77157003, -0.141444  , -0.141413  ,  0.22799   ,
        0.30407301, -0.312805  ,  0.43896899,  0.157057  ,  0.130522  ,
       -0.26506701, -0.017729  ,  0.373034  , -0.63982499,  0.49609199,
        0.43946999,  0.093971  , -0.026262  ,  0.134904  ,  0.119612  ,
        0.34979299,  0.61730999, -0.088111  , -0.36328599, -0.19067299,
       -0.559609  ,  0.198844  , -0.241868  , -0.27721101,  0.044279  ,
       -0.081656  , -0.079494  ,  0.186967  , -0.056997  , -0.13903999,
        0.101553  , -0.147149  ,  0.055064  ,  0.006726  , -0.174288  ,
       -0.30243301, -0.70201099,  0.199955  ,  0.197779  , -0.002215  ,
       -0.34343401, -0.009894  ,  0.15200099,  0.27765799,  0.00

In [5]:
from torch.utils.data import DataLoader 


In [6]:
b=DataLoader(a,batch_size=8)

In [9]:
for batch_idx, samples in enumerate(b):
    print(batch_idx,samples)

0 [tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0

In [13]:
help(b)

Help on DataLoader in module torch.utils.data.dataloader object:

class DataLoader(typing.Generic)
 |  DataLoader(*args, **kwds)
 |  
 |  Data loader. Combines a dataset and a sampler, and provides an iterable over
 |  the given dataset.
 |  
 |  The :class:`~torch.utils.data.DataLoader` supports both map-style and
 |  iterable-style datasets with single- or multi-process loading, customizing
 |  loading order and optional automatic batching (collation) and memory pinning.
 |  
 |  See :py:mod:`torch.utils.data` documentation page for more details.
 |  
 |  Args:
 |      dataset (Dataset): dataset from which to load the data.
 |      batch_size (int, optional): how many samples per batch to load
 |          (default: ``1``).
 |      shuffle (bool, optional): set to ``True`` to have the data reshuffled
 |          at every epoch (default: ``False``).
 |      sampler (Sampler or Iterable, optional): defines the strategy to draw
 |          samples from the dataset. Can be any ``Iterable`

In [29]:
import h5py
import numpy as np

In [34]:
with h5py.File("./output/prep_datasets_dna2vec_test.h5","r") as f:
    # print(f["raw_label"].shape)
    print(f.keys())
    # print(np.array(f["raw_label"]))
    # print(f.get("raw").shape)
    print(f["raw"][0])
    # print(f.get("raw_seq2").shape)
    # print(np.array(f.get("raw"))[2].sum(axis=1))

<KeysViewHDF5 ['X', 'y']>


KeyError: "Unable to synchronously open object (object 'raw' doesn't exist)"

In [27]:
import itertools
import numpy as np
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

def sentence2word(str_set):
    word_seq=[]
    for sr in str_set:
        tmp=[]
        for i in range(len(sr)-5):
            if('N' in sr[i:i+6]):
                tmp.append('null')
            else:
                tmp.append(sr[i:i+6])
        word_seq.append(' '.join(tmp))
    return word_seq

def word2num(wordseq,tokenizer,MAX_LEN):
    sequences = tokenizer.texts_to_sequences(wordseq)
    numseq = pad_sequences(sequences, maxlen=MAX_LEN)
    return numseq

def sentence2num(str_set,tokenizer,MAX_LEN):
    wordseq=sentence2word(str_set)
    numseq=word2num(wordseq,tokenizer,MAX_LEN)
    return numseq

def get_tokenizer():
    f= ['a','c','g','t']
    c = itertools.product(f,f,f,f,f,f)
    res=[]
    for i in c:
        temp=i[0]+i[1]+i[2]+i[3]+i[4]+i[5]
        res.append(temp)
    res=np.array(res)
    NB_WORDS = 4097
    tokenizer = Tokenizer(num_words=NB_WORDS)
    tokenizer.fit_on_texts(res)
    acgt_index = tokenizer.word_index
    acgt_index['null'] = 0
    return tokenizer

def get_data(enhancers,promoters):
    tokenizer=get_tokenizer()
    MAX_LEN=3000
    X_en=sentence2num(enhancers,tokenizer,MAX_LEN)
    MAX_LEN=2000
    X_pr=sentence2num(promoters,tokenizer,MAX_LEN)

    return X_en,X_pr

a,b = get_data("acgtagtcatgc","acgtagttcgat")
print(a)

ModuleNotFoundError: No module named 'tensorflow'

In [55]:
with h5py.File("./output/final_interactions_dna2vec_split.h5","r") as f:
    print(f.keys())
    print(f["raw"].shape)
    # print(np.array(f["raw_label"]))
    # print(np.array(f.get("y")[:]).shape)
    # print(np.array(f.get("raw"))[2].sum(axis=1))

<KeysViewHDF5 ['raw', 'raw_label', 'raw_seq1', 'raw_seq2']>
(94, 1995, 400)


In [37]:
print(torch.get_default_dtype()) 

torch.float32


In [50]:
torch.cuda.device_count()

1

In [12]:
import numpy as np
import torch
a=np.array([[0.5,0.5],
           [0.6,0.2],
           [0.2,0.8]])

In [10]:
a.argmax(dim=1,keepdim=True)

TypeError: argmax() got an unexpected keyword argument 'dim'

In [14]:
pred=torch.tensor(a).argmax(dim=1,keepdim=True)

In [16]:
pred.eq(torch.tensor([0,0,1]).view_as(pred)).sum().item()

3

In [17]:
y_pred = np.array([[0.2, 0.8],
                   [0.7, 0.3],
                   [0.6, 0.4]])

# Get the probability values for each sample and class
sample_indices = [0, 1, 2]  # Indices of the samples you want to retrieve probabilities for
class_indices = [0, 1]  # Indices of the classes you want to retrieve probabilities for

# Retrieve probabilities for the specified samples and classes
selected_probabilities = y_pred[sample_indices][:, class_indices]

In [19]:
y_pred = np.array([[0.2, 0.8, 0.1],
                   [0.7, 0.1, 0.2],
                   [0.3, 0.4, 0.3]])

# Example y_true: a 1D array of true class labels for each sample
y_true = np.array([1, 0, 1])

# Get the probabilities of the correct class for each sample
correct_class_probabilities = y_pred[np.arange(len(y_true)), y_true]

print("Correct Class Probabilities:")
print(correct_class_probabilities)

Correct Class Probabilities:
[0.8 0.7 0.4]


In [23]:
np.r_[np.array([1,2,3]),np.array([2,3,4])]

array([1, 2, 3, 2, 3, 4])

In [1]:
from scipy.interpolate import interp1d

In [4]:
from modules.evaluation.evaluation import ModelEvaluator

In [5]:
fpr,tpr = [[0,0,0.1,0.2,0.5,1],[0,0.1,0.2,1]],[[0,0,0.1,0.2,0.5,1],[0,0.1,0.2,1]]

In [7]:
y_true_list=[]
y_pred_list=[]

In [8]:
model_evaluator = ModelEvaluator(y_true_list=y_true_list, y_pred_list=y_pred_list)

In [9]:
model_evaluator.interp_roc_curve(fpr,tpr)

(array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
        0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
        0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
        0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
        0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
        0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
        0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
        0.70707071, 0.71717172, 0.72727273, 0.73

In [23]:
hyperparameters = {
    'param1': [1, 2, 3],
    'param2': [0.1, 0.01, 0.001],
    'param3': ['a', 'b', 'c'],
    'param4': [],
    'param5': [1]
}

def remove_null_key(hyperparameters):
    # new_dict = hyperparameters
    keys = []
    for (key, val) in hyperparameters.items():
        if len(val) == 0:
            keys.append(key)
    for key in keys:
        del hyperparameters[key]
    return hyperparameters

def generate_param_combinations(hyperparameters):
    
    # 检查是否还有未处理的超参数
    if len(hyperparameters) == 0:
        yield {}  # 返回空字典作为最基本的情况
    else:
        # 取出第一个超参数
        param_name, param_values = next(iter(hyperparameters.items()))
        remaining_hyperparameters = dict(hyperparameters)
        del remaining_hyperparameters[param_name]
        
        
        # 递归生成剩余超参数的组合
        for param_value in param_values:
            for param_combination in generate_param_combinations(remaining_hyperparameters):
                param_combination[param_name] = param_value
                yield param_combination

# 生成超参数组合
# a = remove_null_key(hyperparameters)
# print(a)
param_combinations = list(generate_param_combinations(remove_null_key(hyperparameters)))

# 遍历超参数组合并进行处理
for params in param_combinations:
    # 在这里执行你想要进行的操作，例如训练模型等
    print(f"Current hyperparameters: {params}")

Current hyperparameters: {'param5': 1, 'param3': 'a', 'param2': 0.1, 'param1': 1}
Current hyperparameters: {'param5': 1, 'param3': 'b', 'param2': 0.1, 'param1': 1}
Current hyperparameters: {'param5': 1, 'param3': 'c', 'param2': 0.1, 'param1': 1}
Current hyperparameters: {'param5': 1, 'param3': 'a', 'param2': 0.01, 'param1': 1}
Current hyperparameters: {'param5': 1, 'param3': 'b', 'param2': 0.01, 'param1': 1}
Current hyperparameters: {'param5': 1, 'param3': 'c', 'param2': 0.01, 'param1': 1}
Current hyperparameters: {'param5': 1, 'param3': 'a', 'param2': 0.001, 'param1': 1}
Current hyperparameters: {'param5': 1, 'param3': 'b', 'param2': 0.001, 'param1': 1}
Current hyperparameters: {'param5': 1, 'param3': 'c', 'param2': 0.001, 'param1': 1}
Current hyperparameters: {'param5': 1, 'param3': 'a', 'param2': 0.1, 'param1': 2}
Current hyperparameters: {'param5': 1, 'param3': 'b', 'param2': 0.1, 'param1': 2}
Current hyperparameters: {'param5': 1, 'param3': 'c', 'param2': 0.1, 'param1': 2}
Current

In [8]:
len(hyperparameters)

4

In [10]:
import numpy as np
a = [np.nan,1,2,4,5]
np.nanmax(a)

5.0

In [31]:
def isNumber(f):
    return all([p.isdigit() for p in [f[:f.find('.')], f[f.find('.')+1:]] if len(p)])
def auto_type(s,return_int=True):
    if isNumber(s):
        if return_int:  # 判断是否为数字
            return int(s)
        else:
            return float(s)
    else:
        return s  # 否则返回字符串类型
    
def read_config_file(filename):
    config_dict = {}
    
    with open(filename, 'r') as file:
        for line in file:
            line = line.strip()
            if line:
                key, val = line.split(':')
                key = key.strip().replace(" ","")
                val = val.strip().replace(" ","")
                
                if not val:
                    config_dict[key] = []
                else:
                    config_dict[key] = [auto_type(i,return_int=False) for i in val.split(",")]
    
    return config_dict

config_filename = 'config.txt'
config_data = read_config_file(config_filename)
print(config_data)


{'epochs': [10.0], 'learning_rate': [0.001, 0.01, 0.1, 0.5], 'batch_size': [4.0, 8.0, 16.0, 32.0, 64.0]}


In [39]:
np.random.choice(a,20)

array([nan,  5.,  5.,  2., nan,  1.,  1.,  1.,  5., nan,  5.,  4.,  1.,
        4.,  2.,  5.,  4.,  2.,  2.,  4.])

In [29]:
isNumber("1.01")

True

In [1]:
import torch

In [2]:
device = "cuda"
torch.randn((2, 3), device=device)


tensor([[ 0.8185,  0.8892,  0.0420],
        [-0.0134,  0.3473,  0.1898]], device='cuda:0')

In [3]:
torch.cuda.empty_cache()

In [7]:
torch.cuda.is_available()

True